services:
  api:
    build: .
    env_file: .env
    command: bundle exec rails s -b 0.0.0.0 -p 3000
    ports:
      - "${RAILS_PORT}:3000"
    environment:
      RAILS_ENV: ${RAILS_ENV}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      DATABASE_URL: "postgresql://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}"
    depends_on:
      - db
    volumes:
      - kse_web_data:/app/tmp
      - kse_web_data:/app/log

  db:
    image: postgres:15
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - kse_db_data:/var/lib/postgresql/data

  watchtower:
    image: containrrr/watchtower
    container_name: ${WATCHTOWER_CONTAINER_NAME}
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOCKER_API_VERSION: ${DOCKER_API_VERSION}
    command: >
      sh -c 'if [ "${WATCHTOWER_ENABLED}" = "true" ]; then
        /watchtower --interval 60;
      else
        echo "Watchtower disabled"; sleep infinity;
      fi'

volumes:
  kse_db_data:
  kse_web_data: