name: CI

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read
  checks: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:

          - name: Check for common security misconfigurations
            needs_bundle: true
            run: bundle exec rails_best_practices --only=security

          - name: Check for outdated dependencies
            needs_bundle: true
            run: bundle config unset deployment && bundle outdated --strict

          - name: ERB Lint
            needs_bundle: true
            run: bundle exec erb_lint --lint-all

          - name: Prettier check - Ruby area
            run: npx prettier --check "/app/**.{js,jsx,css,scss,html}"

          - name: Prettier check - Indexer area
            run: npx prettier --check "/indexer/**.{js,jsx,css,scss,html}"

          - name: Prettier check - Crawler area
            run: npx prettier --check "/crawler/**.{js,jsx,css,scss,html}"

          #- name: Check for vulnerable JavaScript dependencies
          #  run: npm audit --audit-level=high

          - name: Zeitwerk check
            run: bin/rails zeitwerk:check

          - name: Scan for common Rails security vulnerabilities using static analysis
            run: bin/brakeman --no-pager
      
          - name: Scan for known security vulnerabilities in gems used
            run: bin/bundler-audit
      
    name: ${{ matrix.name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Sys Depends
        run: sudo apt-get update && sudo apt-get install -y libvips-dev libpq-dev libblas-dev liblapack-dev

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Bundle install
        if: matrix.needs_bundle
        run: bundle install --jobs 4 --retry 3
      
      # None Yet
      #- name: Set up Node.js
      #  uses: actions/setup-node@v6
      #  with:
      #    node-version-file: package.json
      #    cache: 'npm'


      #- name: Install JS dependencies
      #  run: npm ci
      - name: Cache dependencies
        uses: actions/cache@v5
        with:
          path: |
            vendor/bundle
            tmp/rubocop
            **/node_modules
          key: ${{ runner.os }}-deps-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-deps-

      - name: Run ${{ matrix.name }}
        run: ${{ matrix.run }}

# Whats a test
#  test:
#    runs-on: ubuntu-latest
#
#    # services:
#    #  redis:
#    #    image: valkey/valkey:8
#    #    ports:
#    #      - 6379:6379
#    #    options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v6
#
#      - name: Set up Ruby
#        uses: ruby/setup-ruby@v1
#        with:
#          bundler-cache: true
#
#      - name: Run tests
#        env:
#          RAILS_ENV: test
#          # RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
#          # REDIS_URL: redis://localhost:6379/0
#        run: bin/rails db:test:prepare test
