name: CI

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read
  checks: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Check for secrets in code
            run: bin/secret_scanner

          - name: Check for common security misconfigurations
            run: bin/rails_best_practices --only=security


          - name: ERB Lint
            run: bundle exec erb_lint --lint-all

          - name: Check for outdated dependencies
            run: bin/bundle outdated --strict

          - name: Prettier check
            run: bin/prettier --check "**/*.{js,jsx,css,scss,html}"

          - name: Check for vulnerable JavaScript dependencies
            run: npm audit --audit-level=high

          - name: Zeitwerk check
            run: bin/rails zeitwerk:check

          - name: Scan for common Rails security vulnerabilities using static analysis
            run: bin/brakeman --no-pager
      
          - name: Scan for known security vulnerabilities in gems used
            run: bin/bundler-audit
      
    name: ${{ matrix.name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Sys Depends
        run: sudo apt-get update && sudo apt-get install -y libvips-dev libpq-dev

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      
      # None Yet
      #- name: Set up Node.js
      #  uses: actions/setup-node@v6
      #  with:
      #    node-version-file: package.json
      #    cache: 'npm'

      - name: Install JS dependencies
        run: npm ci

      - name: Cache dependencies
        uses: actions/cache@v5
        with:
          path: |
            vendor/bundle
            tmp/rubocop
            **/node_modules
          key: ${{ runner.os }}-deps-${{ hashFiles('**/Gemfile.lock','package-lock.json','**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-deps-

      - name: Run ${{ matrix.name }}
        run: ${{ matrix.run }}
      
  lint:
    runs-on: ubuntu-latest
    env:
      RUBOCOP_CACHE_ROOT: tmp/rubocop
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Cache Ruby gems
        uses: actions/cache@v5
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Prepare RuboCop cache
        uses: actions/cache@v5
        env:
          DEPENDENCIES_HASH: ${{ hashFiles('.ruby-version', '**/.rubocop.yml', '**/.rubocop_todo.yml', 'Gemfile.lock') }}
        with:
          path: ${{ env.RUBOCOP_CACHE_ROOT }}
          key: rubocop-${{ runner.os }}-${{ env.DEPENDENCIES_HASH }}-${{ github.ref_name == github.event.repository.default_branch && github.run_id || 'default' }}
          restore-keys: |
            rubocop-${{ runner.os }}-${{ env.DEPENDENCIES_HASH }}-

      - name: Lint code for consistent style
        run: bin/rubocop -f github

# Whats a test
#  test:
#    runs-on: ubuntu-latest
#
#    # services:
#    #  redis:
#    #    image: valkey/valkey:8
#    #    ports:
#    #      - 6379:6379
#    #    options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v6
#
#      - name: Set up Ruby
#        uses: ruby/setup-ruby@v1
#        with:
#          bundler-cache: true
#
#      - name: Run tests
#        env:
#          RAILS_ENV: test
#          # RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
#          # REDIS_URL: redis://localhost:6379/0
#        run: bin/rails db:test:prepare test
